# Generated by Django 5.1.4 on 2026-05-14 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleArena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_type', models.CharField(choices=[('one_vs_one', '1 vs 1'), ('four_option', '4 Option')], max_length=20)),
                ('question', models.CharField(max_length=150)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('glow', 'Winner Glow'), ('result', 'Result')], default='active', max_length=20)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('glow_ends_at', models.DateTimeField(blank=True, null=True)),
                ('result_delete_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.battlearena')),
            ],
        ),
        migrations.CreateModel(
            name='BattleArenaVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.battlearena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battleoption')),
            ],
            options={
                'unique_together': {('user', 'battle')},
            },
        ),
    ]
