# Generated by Django 5.1.4 on 2026-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_deleted_at_notification_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('updates', 'Updates'), ('promos', 'Promos')], default='admin', max_length=30),
        ),
    ]
