# Generated by Django 5.1.4 on 2026-05-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Green',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
